### ISSUE TITLE
十问XD和OTCBTC平台管理层，请给出正面回答！

### ISSUE THREAD

**Issue by zcxd** [xdite/value-investing-newbie#1]
@郑伊廷 @maple 代OTB社群投资人转下，他们没有途径联系。

1，请问XD和OTCBTC管理层，BTC单价一度接近90000人民币了，请告知你们口中所谓的熊市结束了没有，牛市来了没有？
-------------------------------
2，请问XD和OTCBTC管理层，ETH单价2300了，otb稳如泰山0.17，请问你们采取过哪些有效措施，是否有尊重过OTB持有者的投资行为？
-------------------------------
3，请问XD和OTCBTC管理层，请问平台还有没有用心在经营，还是放任不管，前期无数的种子用户，你们割完韭菜是不是就不管了？那跟骗子还有什么区别？
-------------------------------
4，请问XD和OTCBTC管理层，XD你每天的FB，各种财报说牛逼，各种方法论，各种牛逼得要上天了，各种三年做成功了多少事，请问你哪一件事超过两年了的？哪一件事你不是半途而废，坑死一片人的？你有没有想过被你割了成百上千万的我们这些韭菜的悲愤交加？你有没有想过你的名声为何这么差？你有没有想过为何你不敢开放微博，FB，财报说，知乎等评论，因为被你坑的那一大波人口水都会把你淹没死，为何你自己不反思反而怪他人？
-------------------------------
5，请问XD和OTCBTC管理层，请问XD上次说了句保密协议，一个多月了，还有多久的保密协议期？100年？除了退群踢人，你们还有哪些真正的有效手段？
-------------------------------
6，请问XD和OTCBTC管理层，平台你们还管不管，不管就直接宣布跑路走人，或者找人接手，我们相信任何一个接管的人都要比你做得好不知道多少倍，要管就好好经营，留住用户，宣传推广。
-------------------------------
7，请问XD和OTCBTC管理层，OTB何时归零，你说的20以下随便买，1.8无限收，年底八百，这些从你嘴里崩出来的是人话还是放屁？你对自己的言行有没有一丁点的信任度可言？
-------------------------------
8，李笑来说你是骗子，你反思自己的行为，你现在在广大的千一和各个OTB持有者手里已然成了一个骗子的模样，能否早日醒悟过来，不要自嗨？
-------------------------------
9，想问问XD，你敢不敢把各平台的禁言都取消，看看外界对你的真实评价 看看是李笑来看错了你，还是所有大众用户都看错了你？
-------------------------------
10，最后的最后，一句话：头顶三尺有神明，你望望头顶，看看苍天绕过谁？众多的用户把你抬起来容易，踩你下去也不是不可能，水能载舟亦能覆舟。
-------以上为OTB一众持有者以及平台支持者所写。

**Comment by liushuai** [comment]
头顶三尺有神明，你望望头顶，看看苍天绕过谁？众多的用户把你抬起来容易，踩你下去也不是不可能，水能载舟亦能覆舟。

**Comment by aryehToDog** [comment]
XD 坑我们钱 还钱来!

**Comment by Franky51** [comment]
XD，还我血汗钱
